corazon_patata/urls.py
from django.contrib import admin
from django.urls import path, include
from recipes.views import RecipesList  

urlpatterns = [
    path('accounts/', include('allauth.urls')),  # Include URLs for allauth authentication
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),  # Include URLs for the Summernote editor
    path("", include('recipes.urls'), name="recipes-urls"),  # Include URLs for home and recipes
]

recipes/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.RecipesList.as_view(), name='home'),
    # URL for the recipe list view
    path('<slug:slug>/', views.recipe_detail, name='recipe_detail'),
    # URL for the recipe detail view
    path('recipe/<int:recipe_id>/rate/', views.rate_recipe,
         name='rate_recipe'),
    # URL for rating a recipe
    path('<slug:slug>/edit_comment/<int:comment_id>', views.comment_edit,
         name='comment_edit'),
    # URL for editing a comment
    path('<slug:slug>/delete_comment/<int:comment_id>', views.comment_delete,
         name='comment_delete')
    # URL for deleting a comment
]

recipes/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from cloudinary.models import CloudinaryField
from django.urls import reverse
from django.db.models import Avg


# Create your models here.
class Recipe(models.Model):
    """
   Stores information about a recipe, including title, author, etc,
   related to :model:`auth.User`.
    """
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='recipes')
    featured_image = CloudinaryField('image', default='placeholder')
    description = models.TextField()
    ingredients = models.TextField()
    instructions = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=10,
        choices=[
            ('draft', 'Draft'),
            ('published', 'Published'),
        ],
        default='draft'
    )

    class Meta:
        ordering = ['-created_at', '-author', '-title']

    def __str__(self):
        return self.title

    def __str__(self):
        return f'{self.title} by {self.author.username}'

    def average_rating(self):
        """
        Calculate the average rating for the recipe using
        Django's aggregation for better performance.
        """
        result = self.ratings.aggregate(Avg('rating'))
        # Check if the result is None or empty
        return result['rating__avg'] or 0.0


class Comment(models.Model):
    """
    Model representing a comment on a recipe related to :model:`auth.User`
    and :model:`recipes.Recipe`.
    """
    recipe = models.ForeignKey(
        Recipe, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE,)
    text = models.TextField()
    approved = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f'Comment by {self.user.username} on {self.recipe.title}'


class Rating(models.Model):
    """
    Model representing a rating for a recipe.
    Related to :model:`auth.User` and :model:`recipes.Recipe`.
    Ratings are integers between 1 and 5.
    """
    recipe = models.ForeignKey(
        Recipe, on_delete=models.CASCADE, related_name='ratings')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)]
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        # Ensure a user can only rate a recipe once
        unique_together = ('recipe', 'user')

    def __str__(self):
        return f'{self.user.username} rated {
            self.recipe.title}: {self.rating} stars'

recipes/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

recipes/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.views import generic
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.http import HttpResponseRedirect, JsonResponse
from .models import Recipe, Rating, Comment
from .forms import CommentForm

# Create your views here.


class RecipesList(generic.ListView):
    """
    View to list all recipes.
    Displays a paginated list of recipes with the option to filter by category.

    Context:
    ``recipes``
        A list of :model `Recipe` instances.
    **Template:**
    ``recipes/index.html``
    """
    queryset = Recipe.objects.filter(
        status='published').order_by('-created_at')
    template_name = 'recipes/index.html'  # Template to render the recipe list
    paginate_by = 8  # Number of recipes to display per page


def recipe_detail(request, slug):
    """
    View to display a single recipe.
    Displays a single instance of :model `Recipe` along with its comments
    and ratings.
    It allows users to submit comments and view their own ratings.
    The view handles both GET and POST requests.

    Context:
    ``recipe``
        An instance of :model `Recipe`.
    ``comments``
        A list of comments related to the recipe.
    ``comment_count``
        The number of approved comments for the recipe.
    ``comment_form``
        A form to submit a new comment.
    ``user_rating``
        The user's rating for the recipe, if they are logged in.

     **Template:**
    ``recipes/recipe_detail.html``
    """

    queryset = Recipe.objects.filter(status='published')
    recipe = get_object_or_404(queryset, slug=slug)
    user_rating = None
    comments = recipe.comments.all().order_by("-created_at")
    comment_count = recipe.comments.filter(approved=True).count()

    # Get the user's rating for the recipe if they're logged in
    if request.user.is_authenticated:
        user_rating = Rating.objects.filter(recipe=recipe,
                                            user=request.user).first()
    comment_form = CommentForm()
    if request.method == "POST":
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.recipe = recipe
            comment.save()
            messages.add_message(
                request,
                messages.SUCCESS,
                "Your comment has been submitted and is awaiting approval.",
            )
            # Redirect to the same page to avoid resubmission
            return HttpResponseRedirect(reverse('recipe_detail', args=[slug]))

    return render(
        request,
        'recipes/recipe_detail.html',
        {
            'recipe': recipe,
            'comments': comments,
            'comment_count': comment_count,
            'comment_form': comment_form,
            'user_rating': user_rating,
        }
    )


@login_required
def comment_edit(request, slug, comment_id):
    """
    view to edit comments
    Displays a form to edit an existing comment.
    The view handles both GET and POST requests.

    Context:
    ``recipe``
        An instance of :model `Recipe`.
    ``comment``
        An instance of :model `Comment`.
    ``comment_form``
        A form to edit the comment.

    **Template:**
    ``recipes/recipe_detail.html``

    """
    if request.method == "POST":
        queryset = Recipe.objects.filter(status='published')
        recipe = get_object_or_404(queryset, slug=slug)
        comment = get_object_or_404(Comment, pk=comment_id)
        comment_form = CommentForm(data=request.POST, instance=comment)

        if comment_form.is_valid() and comment.user == request.user:
            comment = comment_form.save(commit=False)
            comment.recipe = recipe
            comment.approved = False
            comment.save()
            messages.add_message(request, messages.SUCCESS, 'Comment Updated!')
        else:
            messages.add_message(
                request, messages.ERROR, 'Error updating comment!')

    return HttpResponseRedirect(reverse('recipe_detail', args=[slug]))


@login_required
def comment_delete(request, slug, comment_id):
    """
    view to delete comment
    Displays a confirmation page to delete an existing comment.
    The view handles both GET and POST requests.

    Context:
    ``recipe``
        An instance of :model `Recipe`.
    ``comment``
        An instance of :model `Comment`.

    **Template:**
    ``recipes/recipe_detail.html``
    """
    queryset = Recipe.objects.filter(status='published')
    recipe = get_object_or_404(queryset, slug=slug)
    comment = get_object_or_404(Comment, pk=comment_id)

    if comment.user == request.user:
        comment.delete()
        messages.add_message(request, messages.SUCCESS, 'Comment deleted!')
    else:
        messages.add_message(
            request, messages.ERROR, 'You can only delete your own comments!')

    return HttpResponseRedirect(reverse('recipe_detail', args=[slug]))


@login_required
@require_POST
def rate_recipe(request, recipe_id):
    """
    View to handle rating a recipe.
    It allows users to rate a recipe from 1 to 5 stars.
    Allows users CRUD operations on their own ratings.
    The `@login_required` decorator ensures that only
    authenticated users can rate recipes.
    Supports standard form submission and AJAX requests.

    Context:
    ``recipe``
        An instance of :model `Recipe`.
    ``rating_value``
        The rating value submitted by the user (1 to 5).
    ``existing_rating``
        The existing rating for the recipe by the user, if any.
    ``is_new_rating``
        A boolean indicating whether the rating is new or
        an update to an existing rating.
    ``new_average``
        The new average rating for the recipe after the rating is submitted.
    ``rating_count``
        The total number of ratings for the recipe.

    **Template:**
    ``recipes/recipe_detail.html``

    **AJAX:**
    - Handles AJAX requests to update the rating without a full page reload.

    **Messages:**
    - Success: "Thank you for your rating!"
    - Error: "Please give a rating value from 1 to 5."

    **Redirects:**
    - Redirects to the recipe detail page after rating.
    """
    recipe = get_object_or_404(Recipe, id=recipe_id)
    rating_value = int(request.POST.get('rating', 0))

    # Validate rating value
    if rating_value < 1 or rating_value > 5:
        if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            return JsonResponse({
                'status': 'error',
                'message': 'Please give a rating value from 1 to 5.'
            }, status=400)

        messages.error(request, "Please give a rating value from 1 to 5.")
        return redirect('recipe_detail', slug=recipe.slug)

    # Check if the user has already rated this recipe
    existing_rating = Rating.objects.filter(
        recipe=recipe, user=request.user).first()
    is_new_rating = existing_rating is None

    if existing_rating:
        # Update the existing rating
        existing_rating.rating = rating_value
        existing_rating.save()
        message = "Your rating has been updated."
    else:
        # Create a new rating
        Rating.objects.create(
            recipe=recipe, user=request.user, rating=rating_value)
        message = "Thank you for your rating!"

    # Calculate the new average rating
    new_average = recipe.average_rating()
    rating_count = recipe.ratings.count()
    if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
        return JsonResponse({
            'status': 'success',
            'average': message,
            'new_average': round(new_average, 1),
            'rating_count': rating_count,
            'is_new_rating': is_new_rating
        })

    # Handle non-AJAX request
    messages.success(request, message)
    return redirect('recipe_detail', slug=recipe.slug)
    # Redirect to the recipe detail page with the updated average rating

recipes/templates/recipes/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<!-- index.html -->

<div class="container-fluid">
    <div class="row">
        <div class="col-12 text-md-center mb-3">
            <h1 class="display-4">Our Recipes</h1>
            <p class="h5">
                Explore our collection of Indo-Mexican recipes and find your next culinary adventure.
            </p>
        </div>
        <!-- Recipes column -->
        <div class="col-12 mt-3 left">
            <div class="row">
                {% for recipe in recipe_list %}
                <div class="col-md-3 mb-1">
                    <div class="card mb-3">
                        <div class="card-body">
                            <div class="image-container">
                                {% if "placeholder" in recipe.featured_image.url %}
                                <img class="card-img-top" src="{% static 'images/default.jpg' %}" alt="placeholder image">
                                {% else %}
                                <img class="card-img-top" src=" {{ recipe.featured_image.url }}" alt="{{ recipe.title }}">
                                {% endif %}
                                <div class="image-flash">
                                </div>
                            </div>
                            <a href="{% url 'recipe_detail' recipe.slug %}">
                                <h2 class="card-title mt-2">{{ recipe.title }}</h2>
                            </a>
                            <hr>
                            <div class="card-text text-muted h6">
                                {{ recipe.description|safe }}
                            </div>
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:4 and not forloop.last %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}

            </div>
        </div>
    </div>
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li>
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                    &laquo; PREVIOUS
                </a>
            </li>
            {% endif %}
            {% if page_obj.has_next %}
            <li>
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                    NEXT &raquo;
                </a>
            </li>
            {% endif %}
    </nav>
    {% endif %}
</div>

<!-- index.html ends -->
{% endblock %}

recipes/templates/recipes/recipe_detail.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

<!-- Meta -->
{% block title %}{{ recipe.title }}{% endblock %}
{% block description %}{{ recipe.description }}{% endblock %}
{% block keywords %}{{ recipe.title }}{% endblock %}

<!-- extra css -->
{% block extra_css %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
{% endblock %}

<!-- recipe_detail.html -->
{% block content %}
<div class="container mt-3">
    <!-- recipe header section -->
    <div class="row mb-4">
        <div class="col-12 text-md-center">
            <h1 class="display-4">{{ recipe.title }}</h1>
            <p class="text-muted">
                By {{ recipe.author.username }} •
                Posted on {{ recipe.created_at|date:"F d, Y" }} •
                {% if recipe.updated_at != recipe.created_at %}
                Updated on {{ recipe.updated_at|date:"F d, Y" }} •
                {% endif %}
            </p>

            <!-- Average Rating Display -->
            <div class="average-rating col-12 text-md-center">
                <div class="d-flex justify-content-center align-items-center mb-3">
                    <div class="stars">
                        {% with avg_rating=recipe.average_rating %}
                            {% for i in "12345" %}
                                {% with counter=forloop.counter|floatformat:"0" %}
                                    {% if counter <= avg_rating|floatformat:"0" %}
                                        <i class="fas fa-star filled" aria-hidden="true"></i>
                                    {% elif counter <= avg_rating|add:0.5|floatformat:"0" %}
                                        <i class="fas fa-star-half-alt filled" aria-hidden="true"></i>
                                    {% else %}
                                        <i class="far fa-star" aria-hidden="true"></i>
                                    {% endif %}
                                {% endwith %}
                            {% endfor %}
                        {% endwith %}
                    </div>
                    <span class="ms-2"> {{ recipe.average_rating|floatformat:1 }} from {{ recipe.ratings.count }} votes</span>
                </div>
            </div>
        </div>
    </div>
    <!-- recipe image and description -->
    <div class="row mb-5">
        <div class="col-md-5">
            <!-- Recipe image -->
            <div class="recipe-image-container mb-3">
                {% if "placeholder" in recipe.featured_image.url %}
                <img src="{% static 'images/default.jpg' %}" alt="placeholder image" class="recipe-image rounded shadow">
                {% else %}
                <img src="{{ recipe.featured_image.url }}" alt="{{ recipe.title }}" class="recipe-image rounded shadow">
                {% endif %}
                
            </div>
            <!-- recipe rating and actions -->
            <div class="text-center">
                <!-- User Rating Form -->
                {% if user.is_authenticated %}
                <div class="card shadow-sm mb-4">
                    <div class="card-body">
                        <h4>Rate this recipe</h4>
                        <form method="post" action="{% url 'rate_recipe' recipe.id %}" id="rating-form">
                            {% csrf_token %}
                            <div class="star-rating">
                                <input type="radio" name="rating" id="star5" value="5" {% if user_rating.rating == 5 %}checked{% endif %}>
                                <label for="star5" title="5 stars"><i class="fas fa-star"></i></label>

                                <input type="radio" name="rating" id="star4" value="4" {% if user_rating.rating == 4 %}checked{% endif %}>
                                <label for="star4" title="4 stars"><i class="fas fa-star"></i></label>

                                <input type="radio" name="rating" id="star3" value="3" {% if user_rating.rating == 3 %}checked{% endif %}>
                                <label for="star3" title="3 stars"><i class="fas fa-star"></i></label>

                                <input type="radio" name="rating" id="star2" value="2" {% if user_rating.rating == 2 %}checked{% endif %}>
                                <label for="star2" title="2 stars"><i class="fas fa-star"></i></label>

                                <input type="radio" name="rating" id="star1" value="1" {% if user_rating.rating == 1 %}checked{% endif %}>
                                <label for="star1" title="1 star"><i class="fas fa-star"></i></label>
                            </div>
                            <div class="text-right">
                                <button type="submit" class="btn btn-primary">Submit Rating</button>
                            </div>
                        </form>
                    </div>
                </div>
                {% else %}
                <div class="card shadow-sm mb-4">
                    <div class="card-body">
                        <p><a href="{% url 'account_login' %}">Log in</a> to rate this recipe.</p>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
        <div class="col-md-7">
            <!-- Recipe description -->
            <div class="card shadow-sm">
                <div class="card-body">
                    <h3 class="card-title">About this Recipe</h3>
                    <div class="card-text">{{ recipe.description|safe }}<br></div>
                    <!-- ingredients card -->
                    <div class="card shadow-sm h-100">
                        <div class="card-header bg-light">
                            <h3 class="card-title mb-0">Ingredients</h3>
                        </div>
                        <div class="card-body">
                            {{ recipe.ingredients|safe }}
                        </div>
                    </div>
                    <!-- Instructions card -->
                    <div class="card shadow-sm h-100">
                        <div class="card-header bg-light">
                            <h3 class="card-title mb-0">Instructions</h3>
                        </div>
                        <div class="card-body">
                            {{ recipe.instructions|safe }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <!-- Displaying count of comments -->
    <div class="row">
        <div class="col-12">
            <strong class="text-secondary">
                <i class="far fa-comments"></i> {{ comment_count }}
            </strong>
        </div>
        <div class="col-12">
            <hr>
        </div>
    </div>

    <!-- Displaying Comments -->
    <div class="row">
        <div class="col-md-8 card mb-4 mt-3 ">
            <div class="card-body">
                <h3>Comments:</h3>
                {% if comments %}
                    {% for comment in comments %}
                        <div class="p-2 comments {% if not comment.approved and comment.user == user %}
                        faded
                        {% elif not comment.approved %}d-none{% endif %}">
                            <p class="text-muted">
                                {{ comment.user }} wrote on
                                {{ comment.created_at }}:
                            </p>
                            <div id="comment{{ comment.id }}">
                                {{ comment.text | linebreaks }}
                            </div>
                            {% if not comment.approved and comment.user == user %}
                            <p class="text-muted mt-2">
                                *This comment is awaiting approval.
                            </p>
                            {% endif %}
                            {% if user.is_authenticated and comment.user == user %}
                            <button class="btn btn-delete"
                            data-comment_id="{{ comment.id }}">Delete</button>
                            <button class="btn btn-edit" data-comment_id="{{ comment.id }}">Edit</button>
                            {% endif %}
                        </div>
                    {% endfor %}
                {% else %}
                <p class="text-muted">No comments yet. Be the first to leave a comment!</p>
                {% endif %}
            </div>
        </div>
        <!-- Creating New Comments -->
        <div class="col-md-4 card mb-4 mt-3">
            <div class="card-body">
                {% if user.is_authenticated %}
                <h3>Leave a comment:</h3>
                <p>Posting as: {{ user.username }}</p>
                <form id="commentForm" method="post" style="margin-top: 1.3em;">
                    {{ comment_form | crispy }}
                    {% csrf_token %}
                    <button id="submitButton" type="submit" class="btn btn-signup btn-lg">Submit</button>
                </form>
                {% else %}
                <p><a href="{% url 'account_login' %}">Log in</a> to leave a comment.</p>
                {% endif %}
            </div>
        </div>
    </div>
</div>
<!-- Delete confirmation modal -->
<div class="modal fade" id="deleteModal" tabindex="-1"
  aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"
          id="deleteModalLabel">Delete comment?</h5>
        <button type="button" class="btn-close"
          data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete your comment?
        This action cannot be undone.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary"
          data-bs-dismiss="modal">Close</button>
        <a id="deleteConfirm" href="#" class="btn
          btn-danger">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}
{% block extras %}
<script src="{% static 'js/comments.js' %}"></script>
{% endblock %}